"""empty message

Revision ID: e6f7749f5267
Revises: 13a72dd926c7
Create Date: 2020-03-14 03:57:41.768051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f7749f5267'
down_revision = '13a72dd926c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_profiles_gender_key', 'user_profiles', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_profiles_gender_key', 'user_profiles', ['gender'])
    # ### end Alembic commands ###
